config/routes.rb
Rails.application.routes.draw do
  get 'toppages_show', to: 'toppages#show'
  
  root to: 'toppages#index'
  resources :toppages, only: [:index, :show]
  
  resources :restaurants, only: [:index] do
    resources :likes, only: [:show, :new, :create, :destroy]
    member do 
      get :followers
      get :reviewers
    end
  end
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :approvings
      get :reviewings
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  
  validates :review_title, presence: true, length: { maximum: 20 }
  validates :score, presence: true
  validates :review_contents, length: { maximum: 500 }
  validates_uniqueness_of :restaurant_id, scope: :user_id
  
  mount_uploader :review_image, ImagesUploader
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :new, :create, :destroy]
  before_action :correct_user, only: [:destroy]
  before_action :review_existing?, only: [:show, :destroy]
  
  def show
    @review = Like.find(params[:id])
  end
  
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @like = Like.new
  end
  
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    
    @like = Like.new(
    restaurant_id: params[:restaurant_id],
    user_id: current_user.id,
    review_name: current_user.name,
    restaurant_name: @restaurant.rest_name,
    review_title: params[:like][:review_title],
    review_contents: params[:like][:review_contents],
    score: params[:like][:score],
    review_image: params[:like][:review_image]
    )
    
    if @like.save
      flash[:success] = 'レビューの投稿に成功しました'
      redirect_to reviewings_user_path(current_user)
    else
      flash[:danger] = 'レビューの投稿に失敗しました'
      render :new
    end
  end
  
  def destroy
   @like = Like.find(params[:id])
   @like.destroy if @like
   flash[:success] = 'レビューを削除しました'
   redirect_to reviewings_user_path(current_user)
  end
  
  private
  
  def correct_user
    review = Like.find(params[:id])
    user = User.find_by(id: review.user_id)
    unless current_user == user
      redirect_to root_url
    end
  end
  
  def review_existing? 
    review = Like.find_by(id: params[:id])
    unless review
      flash[:danger] = '存在しないレビューです'
      redirect_to root_url
    end
  end

end

app/helpers/likes_helper.rb
module LikesHelper
  
  def like_finder(restaurant)
    @like = Like.find_by(user_id: current_user.id, restaurant_id: restaurant.id)
  end
  
  def rest_find(review)
    review = Like.find_by(id: review.id)
    @restaurant = Restaurant.find_by(id: review.restaurant_id)
  end
  
  def user_find(review) 
    review = Like.find_by(id: review.id)
    @user = User.find_by(id: review.user_id)
  end
  
end

app/views/likes/new.html.erb
<div class="text-center mb-4">
  <h1>"<span class="bold"><%= @restaurant.rest_name %></span> "のレビュー投稿ページ</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3 mb-4">
    <%= image_tag @restaurant.rest_image, class: 'review-image' %>
  </div>
</div>

<div class="review-form">
  <%= form_with(model: [@restaurant, @like], url: restaurant_likes_path(@restaurant, @ilke) , local: true) do |f| %> 
  <%= render 'layouts/error_messages', model: f.object %>
  
  <div class="row mt-2">
    <div class="offset-sm-3 col-sm-6 mb-4">
      <%= f.label :review_title, 'タイトル', class: 'bold' %>
      <%= f.text_field :review_title, class: 'form-control', placeholder: 'タイトルは20字以内です' %> 
    </div>
  </div>
  
  <div class="row">
    <div class="offset-sm-3 col-sm-6 mb-4">
      <%= f.label :score, '評価', class: 'bold' %>
      <%= f.hidden_field :score, id: :rest_rating %> 
      <div id="star-rating"></div>
      <script>
        $('#star-rating').raty({
          path: '/assets/',
          click: function(score, e) {
          $("#rest_rating").val(score)
          }
        });
      </script>
    </div>
  </div>
  
  <div class="row">
    <div class="offset-sm-3 col-sm-6 mb-4">
      <%= f.label :review_contents, 'レビュー内容', class: 'bold' %>
      <%= f.text_field :review_contents, class: 'form-control', placeholder: 'レビュー内容を500字以内で記述してください' %> 
    </div>
  </div>
  
  <div class="row">
    <div class="offset-sm-3 col-sm-6 mb-4">
      <%= f.label :review_image, '画像', class: 'bold' %>
      <div>
        <%= f.file_field :review_image %> 
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="offset-sm-3 col-sm-6 mb-4 mt-2">
      <%= f.submit 'レビューを投稿する', class: 'btn btn-block btn-success' %>
    </div>
  </div>
  
  <% end %>
  
  <div class="row">
    <div class="offset-sm-3 col-sm-6 mb-4 mt-2">
      <%= link_to '戻る', :back, class: 'btn btn-block btn-primary' %>
    </div>
  </div>

</div>

app/views/likes/show.html.erb
<div class="text-center mb-5">
  <h1>" <span class="bold"><%= @review.restaurant_name %></span> "へのレビュー詳細</h1>
</div>

<div class="review-name text-center mb-5">
  <div class="row">
    <div class="col-sm-6 mb-2 bold">
      投稿者
    </div>
    <div class="col-sm-6 break-style">
      <%= @review.review_name %>
    </div>
  </div>
</div>

<div class="review-time text-center mb-5">
  <div class="row">
    <div class="col-sm-6 mb-2 bold">
      投稿日時
    </div>
    <div class="col-sm-6 break-style">
      <%= @review.created_at %>
    </div>
  </div>
</div>

<div class="review-title text-center mb-5">
  <div class="row">
    <div class="col-sm-6 mb-2 bold">
      タイトル
    </div>
    <div class="col-sm-6 break-style">
      <%= @review.review_title %>
    </div>
  </div>
</div>

<div class="review-score text-center mb-5">
  <div class="row">
    <div class="col-sm-6 mb-2 bold">
      評価
    </div>
    <div class="col-sm-6">
      <p><%= @review.score %></p>
      <div id="star-rate-<%= @review.id %>" class="mb-2"></div>
      <script>
        $('#star-rate-<%= @review.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= @review.score %>,
        });
      </script> 
    </div>
  </div>
</div>

<div class="review-name text-center mb-5">
  <div class="row">
    <div class="col-sm-6 mb-2 bold">
      レビュー内容
    </div>
    <div class="col-sm-6 break-style">
      <%= @review.review_contents %>
    </div>
  </div>
</div>

<div class="review-name text-center mb-5">
  <div class="row">
    <div class="col-sm-6 mb-2 bold">
      レビュー画像
    </div>
    <div class="col-sm-6">
      <%= image_tag @review.review_image.url if @review.review_image? %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3 mb-3">
    <% if current_user == user_find(@review) %>
      <%= link_to '削除する', restaurant_like_path(rest_find(@review),@review), method: :delete, class: 'btn btn-danger btn-block' %> 
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= link_to '戻る', :back, class: 'btn btn-block btn-primary' %>
  </div>
</div>
  