config/routes.rb
Rails.application.routes.draw do
  get 'toppages_show', to: 'toppages#show'
  
  root to: 'toppages#index'
  resources :toppages, only: [:index, :show]
  
  resources :restaurants, only: [:index] do
    resources :likes, only: [:show, :new, :create, :destroy]
    member do 
      get :followers
      get :reviewers
    end
  end
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :approvings
      get :reviewings
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :birth, presence: true
  validates :contents, length: { maximum: 200 }
  has_secure_password
  
  has_many :favorites
  has_many :approvings, through: :favorites, source: :restaurant
  
  has_many :likes
  has_many :reviewings, through: :likes, source: :restaurant
  
  
  def approve(restaurant)
    self.favorites.find_or_create_by(restaurant_id: restaurant.id)
  end
  
  def unapprove(restaurant)
    approving = self.favorites.find_by(restaurant_id: restaurant.id)
    approving.destroy if approving
  end
  
  def approvings?(restaurant)
    self.approvings.include?(restaurant)
  end
  
  def reviewings?(restaurant)
    self.reviewings.include?(restaurant)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :user_existing?, only: [:show, :edit, :update]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(20)
  end
  
  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params_create)
    
    if @user.save
      flash[:success] = '登録に成功しました'
      redirect_to @user
    else
      flash[:danger] = '登録に失敗しました'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    unless current_user.id == @user.id 
      redirect_to root_url
    end
    
    if @user.update(user_params_edit)
      flash[:success] = '正常に更新されました'
      redirect_to @user
    else
      flash[:danger] = '更新に失敗しました'
      render :edit
    end
  end
  
  def approvings 
    @user = User.find(params[:id])
    @approvings = @user.approvings.page(params[:page])
  end
  
  def reviewings
    @user = User.find(params[:id])
    @reviews = Like.where(user_id: @user.id).page(params[:page]).per(20)
  end
  
  private
  
  def user_params_create()
    params.require(:user).permit(:name, :email, :birth, :password, :password_confirmation)
  end
  
  def user_params_edit() 
    params.require(:user).permit(:name, :email, :birth, :contents)
  end
  
  def user_existing?
    @user = User.find_by(id: params[:id])
    unless @user
      flash[:danger] = 'ユーザーが存在しません'
      redirect_to root_url
    end
  end

	def correct_user
    @user = User.find_by(id: params[:id])
    unless current_user == @user
      flash[:danger] = '不正なアクセスです'
      redirect_to root_url
    end
	end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
  
  def count_approvings(user) 
		@count_approvings = user.approvings.count
  end
	
	def count_reviewings(user)
	  @count_reviewings = user.reviewings.count
	end
	
end

app/views/users/approvings.html.erb
<div class="text-center mb-5">
  <h1>" <%= @user.name %> "さんのお気に入り一覧</h1>
</div>

<div class="favoite-restaurants">
  <%= render 'layouts/restaurants', restaurants: @approvings %>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <%= link_to 'トップページに戻る', root_path, class: 'btn btn-block btn-primary mt-3' %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="text-center mb-5">
  <h1>ユーザー情報の変更</h1>
</div>

<div class="text-center">
  <%= form_with(model: @user, local: true) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      
      <div class="form-group mb-5">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class="form-group mb-5">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group mb-5">
        <%= f.label :birth, '生年月日' %>
        <%= raw sprintf(f.date_select(:birth, use_month_numbers: true, start_year: 1930, end_year: (Time.now.year + 5), default: Date.new(1990, 1, 1), date_separator: '%s'), '年 ', '月 ') + '日' %>
      </div>
      
      <div class="form-group mb-5">
        <%= f.label :contents, '自己紹介文' %>
        <%= f.text_field :contents, class: 'form-control' %>
      </div>
      
      <%= f.submit '更新する', class: 'btn btn-block btn-success mb-4' %>
      
      <%= link_to '戻る', @user, class: 'btn btn-block btn-primary' %>
    </div>
  </div>
  
  <% end %>
</div>

app/views/users/index.html.erb
<div class="text-center mb-5">
  <h1>User一覧</h1>
</div>

<%= render 'layouts/users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
      <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group mb-4">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group mb-4">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      
      <div class="form-group mb-4">
        <%= f.label :birth, '生年月日', class: 'mr-4' %>
        <%= raw sprintf(f.date_select(:birth, use_month_numbers: true, start_year: 1930, end_year: (Time.now.year + 5), default: Date.new(1990, 1, 1), date_separator: '%s'), '年 ', '月 ') + '日' %>
      </div>
      
      <div class="form-group mb-4">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>   

      <div class="form-group mb-4">
        <%= f.label :password_confirmation, 'パスワード確認用' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>   
      
      <%= f.submit '送信', class: 'btn btn-block btn-success' %>
      
      <% end %>
  </div>
</div>

app/views/users/reviewings.html.erb
<div class="text-center mb-5">
  <h1>"<%= @user.name %>"さんのレビュー</h1>
</div>

<%= render 'layouts/reviews', reviews: @reviews %>

app/views/users/show.html.erb
<div class="text-center mb-5">
  <h2>ユーザー情報</h2>
</div>

<div class="text-center">
  <div class="row mb-5">
    <div class="col-sm text-center"><img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt=""></div>
  </div>
  
  <div class="row mb-5">
    <div class="col-sm-3 offset-sm-3 text-center bold">名前 : </div>
    <div class="col-sm-3 text-center break-style"><%= @user.name %></div>
  </div>

  <div class="row mb-5">
    <div class="col-sm-3 offset-sm-3 text-center bold">メールアドレス : </div>
    <div class="col-sm-3 text-center break-style"><%= @user.email %></div>
  </div>

  <div class="row mb-5">
    <div class="col-sm-3 offset-sm-3 text-center bold">生年月日 : </div>
    <div class="col-sm-3 text-center"><%= @user.birth %></div>
  </div>

  <div class="row mb-5">
    <div class="col-sm-3 offset-sm-3 text-center bold">紹介文 : </div>
    <div class="col-sm-3 text-center break-style"><%= @user.contents %></div>
  </div>
  
  <div class="row mb-5">
    <div class="col-sm-3 offset-sm-3 text-center bold">お気に入りしている数 : </div>
    <div class="col-sm-3 text-center"><%= count_approvings(@user) %>  <span><%= link_to 'お気に入り一覧を見る', approvings_user_path(@user) %></span></div>
  </div>
  
  <div class="row mb-5">
    <div class="col-sm-3 offset-sm-3 text-center bold">レビューしている数 : </div>
    <div class="col-sm-3 text-center"><%= count_reviewings(@user) %>  <span><%= link_to 'レビューを見る', reviewings_user_path(@user) %></span></div>
  </div>
</div>

<div class="row mb-3">
  <div class="col-sm-6 offset-sm-3">
    <% if current_user.id == @user.id %>
      <%= link_to '内容を編集する', edit_user_path, class: 'btn btn-block btn-success mb-4' %>
      <%= link_to '戻る', :back, class: 'btn btn-block btn-primary mb-4' %>
    <% else %>
      <%= link_to '戻る', :back, class: 'btn btn-block btn-primary mb-4' %>
    <% end %>
  </div>
</div>