config/routes.rb
Rails.application.routes.draw do
  get 'toppages_show', to: 'toppages#show'
  
  root to: 'toppages#index'
  resources :toppages, only: [:index, :show]
  
  resources :restaurants, only: [:index] do
    resources :likes, only: [:show, :new, :create, :destroy]
    member do 
      get :followers
      get :reviewers
    end
  end
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :approvings
      get :reviewings
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
   
  end

  def show
    
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/toppages/index.html.erb
<div class="toppage">
  <div class="text-center header-title mb-4">
    <%= image_tag asset_path('title.png'), class: 'header-logo' %>
  </div>
    
  <% if logged_in? %>
   
  <%# カルーセルスライダー %>
  <div class="row">
    <div class="col-sm-6 offset-sm-3 mb-5">
	    <ul class="slider">
	      <li><%= image_tag asset_path('french.png') %></li>
	      <li><%= image_tag asset_path('kominka.png') %></li>
	      <li><%= image_tag asset_path('yatai.png') %></li>
	    </ul>
	  </div>
  </div>

  
  <div class="text-center mb-4">
    <h5 class="search_icon">お店を検索してみよう！<span class="fas fa-search ml-2"></span></h5>
  </div>
  <div class="row">
    <div class="col-sm-6 offset-sm-3">
      <div class="search_field">
        <%= form_with(url: restaurants_path, scope: :search, local: true, method: :get) do |f| %>
        
        <div class="form-group">
          <%= f.text_field :freeword_field, class:'form-control' %>
        </div>
          <%= f.submit '検索！', class: 'btn btn-block btn-primary' %>
        <% end %>
      </div>

    </div>
  </div>
  
  <% else %>
  <%# 非ログイン時のトップページ %>
  <div class="row">
    <div class="offset-sm-3 col-sm-6">
      <%= link_to '新規登録', new_user_path, class: 'btn btn-block btn-success mb-5' %>
      <%= link_to 'ログイン', login_path, class: 'btn btn-block btn-primary' %>
    </div>
  </div>
  
  <% end %>

  
</div>
  

  

app/views/toppages/show.html.erb
<div class="text-center jumbotron">
  <h1 class="mb-5">Q & A</h1>
  
<div class="panel-group" id="accordion">
  
  <div class="panel panel-default mb-3">
    <div class="panel-heading row">
      <h4 class="panel-title col-sm-6 offset-sm-3">
        <button type="button" class="btn btn-block btn-dark mb-2" data-toggle="collapse" data-parent="#accordion" href="#collapse3">「ミセサガシ」の使い方は？</button>
      </h4>
    </div>
    <div id="collapse3" class="panel-collapse collapse in row">
      <div class="panel-body col-sm-6 offset-sm-3 text-center">
        <p class="mb-3">自分の気になるお店を検索するサイト。</p>
        <p class="mb-3">自分だけのお気に入りのお店を見つけよう！</p>
        <p class="mb-3">新規登録は <%= link_to 'こちら', new_user_path %> から！</p>
        <p class="mb-3">ログインは <%= link_to 'こちら', login_path %> から！</p>
      </div>
    </div>
  </div>
  
  <div class="panel panel-default mb-3">
    <div class="panel-heading row">
      <h4 class="panel-title col-sm-6 offset-sm-3">
        <button type="button" class="btn btn-block btn-dark mb-2" data-toggle="collapse" data-parent="#accordion" href="#collapse4">「お気に入り機能」ってなに？</button>
      </h4>
    </div>
    <div id="collapse4" class="panel-collapse collapse row">
      <div class="panel-body col-sm-6 offset-sm-3 text-center">
        <p class="mb-3">自分の興味のあるお店をお気に入り登録するだけで、いつでもどこでも閲覧可能！</p>
        <p class="mb-3">お気に入り登録するには「お気に入り登録」ボタンをクリック！<i class="far fa-thumbs-up"></i></p>
        <div class="text-center mb-3"><%= image_tag asset_path('favorite_button_inst.png'), class: 'review-image' %></img></div>
      </div>
    </div>
  </div>
  
  <div class="panel panel-default mb-3">
    <div class="panel-heading  row">
      <h4 class="panel-title col-sm-6 offset-sm-3">
        <button type="button" class="btn btn-block btn-dark mb-2" data-toggle="collapse" data-parent="#accordion" href="#collapse5">「レビュー機能」とは？</button>
      </h4>
    </div>
    <div id="collapse5" class="panel-collapse collapse row">
      <div class="panel-body col-sm-6 offset-sm-3 text-center">
        <p class="mb-3">自分が行ったお店を評価しよう！</p>
        <p class="mb-3">あなたの経験が他の人の役に立つこと間違いなし！</p>
      </div>
    </div>
  </div>
  
</div>
  
  <div class="text-center">
    <%= link_to 'さっそく検索する', root_path, class: 'btn btn-success' %>
  </div>
</div>