config/routes.rb
Rails.application.routes.draw do
  get 'toppages_show', to: 'toppages#show'
  
  root to: 'toppages#index'
  resources :toppages, only: [:index, :show]
  
  resources :restaurants, only: [:index] do
    resources :likes, only: [:show, :new, :create, :destroy]
    member do 
      get :followers
      get :reviewers
    end
  end
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :approvings
      get :reviewings
    end
  end
  
  resources :favorites, only: [:create, :destroy]
  
end

app/views/layouts/_approve_button.html.erb
<%# レストラン一覧表示の時に用いるお気に入りボタン %>
<div class="approve-button mb-3">
<% if current_user.approvings?(restaurant) %>
  <%= form_with(model: current_user.favorites.find_by(restaurant_id: restaurant.id), local: true, method: :delete) do |f| %>
    <%= hidden_field_tag :restaurant_id, restaurant.id %>
    <%= f.submit 'お気に入り解除', class: 'btn btn-block btn-danger' %>
  <% end %>
  
<% else %>
  <%= form_with(model: current_user.favorites.build, local: true) do |f| %>
    <%= hidden_field_tag :restaurant_id, restaurant.id %>
    <%= f.submit 'お気に入り登録', class: 'btn btn-block btn-success' %>
  <% end %>

<% end %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_follow_button.html.erb
<%# レストラン一覧表示の時に用いるレビューボタン %>
<div class="follow-button mb-3">
  
<% if current_user.reviewings?(restaurant) %>
<%# すでにレビューしている場合はlikes#destroyへ飛ばす %>
    <%= link_to 'レビューを削除する', restaurant_like_path(restaurant, like), method: :delete, class: 'btn btn-block btn-danger' %>
  
  
<% else %>
<%# まだレビューしていない場合はlikes#newへ飛ばす %>
  <%= link_to 'レビューを投稿する', new_restaurant_like_path(restaurant), class: 'btn btn-success btn-block' %>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="mb-4">
  
<% if logged_in? %>
  <%# ログイン時のナビゲーションバー %>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <%= link_to 'ミセサガシ', root_path, class: 'navbar-brand' %>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div id="nav-bar" class="navbar-collapse collapse justify-content-end">
        <ul class="navbar-nav">
          <li class="nav-item"><a class="nav-link" href="<%= users_path %>">User一覧</a></li>
          <li class="nav-item"><a class="nav-link" href="<%= toppages_show_path %>">Q & A</a></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <div class="dropdown-menu dropdown-menu-right">
              <%= link_to 'Profile', user_path(current_user), class: 'dropdown-item' %>
              <a class="dropdown-item" href="<%= approvings_user_path(current_user) %>">お気に入り一覧<span class="badge badge-secondary ml-2"><%= count_approvings(current_user) %></span></a>
              <a class="dropdown-item" href="<%= reviewings_user_path(current_user) %>">レビュー一覧<span class="badge badge-secondary ml-2"><%= count_reviewings(current_user) %></span></a>
              <%= link_to 'ログアウト', logout_path(current_user),method: :delete, class: 'dropdown-item' %>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    
<% else %> 
  <%# 非ログイン時のナビゲーションバー %>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <%= link_to 'ミセサガシ', root_path, class: 'navbar-brand' %>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#nav-bar">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div id="nav-bar" class="navbar-collapse collapse justify-content-end">
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to 'このサイトについて', toppages_show_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '新規登録', new_user_path, class: 'nav-link' %></li>
        </ul>
      </div>
    </nav>
  
<% end %>
</div>

app/views/layouts/_restaurants.html.erb
<%#　レストラン一覧の表示 %>
<div class="rest-index">
    <% restaurants.each do |restaurant| %>
  <div class="rest-list">
    <%# レストランの情報詳細 %>
    <div class="row mb-4">
      <div class="col-sm-6 text-center">
        <div class="mb-2 text-center"><img class="rest-image" src="<%= restaurant.rest_image %>" alt="<%= restaurant.rest_id %>の画像"></img></div>
      </div>
      <div class="col-sm-6">
        <div class="mb-2"><span style="font-weight: bold;" class="rest-name"><%= restaurant.rest_name %></span></div> 
        <div class="mb-2"><span class="rest-place"><%= restaurant.rest_place %></span></div>
        <div class="mb-4"><span class="rest-phone"><%= restaurant.rest_phone %></span></div>  
        <div class="mb-2"><span class="rest-contents"><%= restaurant.rest_contents %></span></div>
      </div>
    </div>
      
    
    <%# レストランの詳細ページに移行するボタンとお気に入りボタン %>
    <div class="col-sm-6 offset-sm-3">
      <div class="mb-4">
        <span class="rest-image"><%= link_to '詳細を見る', restaurant.rest_url, class: 'btn btn-block btn-info mb-3' %></span>
        <div class="rest-app mb-3 text-center">このお店は <%= count_approved(restaurant) %> 人にお気に入りされています！</div>
        <%= render 'layouts/approve_button', restaurant: restaurant %>
        <div class="rest-fol mb-3 text-center"><%= count_reviewers(restaurant) %> レビュー
          <span>
            <%= link_to 'このお店にレビューしたUser', reviewers_restaurant_path(restaurant), class: 'ml-2' %>
          </span>
        </div>
        <%= render 'layouts/follow_button', restaurant: restaurant, like: like_finder(restaurant) %>
      </div>
    </div>
    </div>
    
    <% end %>
  
  <div class="text-center"><%= paginate restaurants %></div>
</div>

app/views/layouts/_reviews.html.erb
<% reviews.each do |review| %>
  <div class="row mb-4 review-list">
    <div class="col-sm-2">
      <p class="review-name break-style text-center mb-5" style="font-weight: bold;"><%= link_to review.review_name, user_find(review) %></p>
      <p class="review-show text-center mb-3"><%= link_to '詳細をみる', restaurant_like_path(rest_find(review),review), class: 'btn btn-info' %></p>
      
      <% if current_user == user_find(review) %>
      <p class="text-center"><%= link_to '削除', restaurant_like_path(rest_find(review),review), method: :delete, class: 'btn btn-danger' %></p> 
      <% end %>
      
    </div>
    <div class="col-sm-6">
      <p class="mb-2 break-style">" <span style="font-weight: bold;"><%= link_to review.restaurant_name, rest_url(review) %></span> "へのレビュー</p>
      <p class="created-at mb-2">created at : <%= review.created_at %></p>
      <h4 class="review-title mb-2 break-style">評価 : <%= review.score %> 点 | <%= review.review_title %></h4>
      <div id="star-rate-<%= review.id %>" class="mb-2"></div>
      <script>
        $('#star-rate-<%= review.id %>').raty({
          size: 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          half: true,
          readOnly: true,
          score: <%= review.score %>,
        });
      </script> 
      
      <p class="review-contents break-style mb-2 overflow"><%= review.review_contents %></p>
    </div>
    <div class="col-sm-4">
      <div class="review-image"><%= image_tag review.review_image.url if review.review_image? %></div>
    </div>
  </div>
  
<% end %>

<%= paginate reviews %>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= link_to 'トップページへ', root_path, class: 'btn btn-block btn-primary mb-2' %>
  </div>
</div>

app/views/layouts/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
    <div class="row">
      <div class="col-sm-3 offset-sm-4">
        <li class="media mb-3">
            <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 60 }) %>" alt="">
          <div class="media-body">
            <div>
              <span style="font-weight: bold;" class="break-style"><%= user.name %></span>
            </div>
            <div>
              <p class="mb-2 overflow break-style"><%= user.contents %></p>
            </div>
          </div>
        </li>
      </div>
      <div class="col-sm-3">
        <p><%= link_to 'View profile', user_path(user), class: 'btn btn-success' %></p>
      </div>
    </div>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ミセサガシ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar', user: @user %>
    <div class="container">
      
      <%= render 'layouts/flash_messages' %>
    
      <%= yield %>
    
      <a href="#" class="back-to-top">▲</a>
    </div>
  </body>
</html>